# Generated by Django 3.1.1 on 2020-10-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0002_auto_20201013_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='datereg',
            field=models.DateTimeField(),
        ),
    ]
