# Generated by Django 3.1.1 on 2020-10-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0003_auto_20201013_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='id',
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='firstname',
            field=models.CharField(db_column='FIRSTNAME', max_length=200),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='lastname',
            field=models.CharField(db_column='LASTNAME', max_length=200),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(db_column='PASSWORD', max_length=200),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='useremail',
            field=models.EmailField(db_column='USEREMAIL', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(db_column='USERNAME', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='userregistration',
            table='registered_users',
        ),
    ]
