# Generated by Django 3.1.1 on 2020-10-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0004_auto_20201013_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
