# Generated by Django 3.1.1 on 2020-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0006_userregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='useremail',
            field=models.EmailField(db_column='USEREMAIL', max_length=200),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(db_column='USERNAME', max_length=200, primary_key=True, serialize=False),
        ),
    ]
