# Generated by Django 3.1.1 on 2020-10-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0007_auto_20201013_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
