# Generated by Django 3.1.1 on 2020-10-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0011_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
