# Generated by Django 3.1.1 on 2020-11-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0013_userregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOfRepsBills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_bill', models.TextField(blank=True, db_column='title_of_bill', null=True)),
                ('date', models.TextField(blank=True, db_column='date', null=True)),
                ('category', models.TextField(blank=True, db_column='category', null=True)),
                ('chamber', models.TextField(blank=True, db_column='chamber', null=True)),
                ('status', models.TextField(blank=True, db_column='status', null=True)),
                ('stage_of_bill', models.TextField(blank=True, db_column='stage_of_bill', null=True)),
                ('portfolio', models.TextField(blank=True, db_column='portfolio', null=True)),
                ('summary', models.TextField(blank=True, db_column='summary', null=True)),
                ('link_to_bill', models.TextField(blank=True, db_column='link_to_bill', null=True)),
            ],
            options={
                'db_table': 'hrepsbills',
            },
        ),
    ]
