# Generated by Django 3.1.1 on 2020-11-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0014_houseofrepsbills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseOfRepsBills',
        ),
    ]
