# Generated by Django 3.1.1 on 2020-11-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0016_houseofrepsbills'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrepsPoliticiansInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_column='name', null=True)),
                ('elec_div', models.TextField(blank=True, db_column='for', null=True)),
                ('position', models.TextField(blank=True, db_column='position', null=True)),
                ('party', models.TextField(blank=True, db_column='party', null=True)),
                ('phone_number', models.TextField(blank=True, db_column='phone_number', null=True)),
                ('email_address', models.TextField(blank=True, db_column='email_address', null=True)),
                ('twitter', models.TextField(blank=True, db_column='twitter', null=True)),
                ('facebook', models.TextField(blank=True, db_column='facebook', null=True)),
                ('bio_link', models.TextField(blank=True, db_column='bio_link', null=True)),
                ('profile_picture', models.TextField(blank=True, db_column='profile_picture', null=True)),
            ],
            options={
                'db_table': 'hrepsMembers',
            },
        ),
    ]
