# Generated by Django 3.1.1 on 2020-11-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0017_hrepspoliticiansinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='hrepspoliticiansinfo',
            name='elec_div',
            field=models.TextField(blank=True, db_column='elec_div', null=True),
        ),
    ]
