# Generated by Django 3.1.1 on 2020-11-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackgovApp', '0018_auto_20201123_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrepsVotePatterns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_column='title', null=True)),
                ('div_no', models.TextField(blank=True, db_column='div_no', null=True)),
                ('question', models.TextField(blank=True, db_column='question', null=True)),
                ('date', models.TextField(blank=True, db_column='date', null=True)),
                ('outcome', models.TextField(blank=True, db_column='outcome', null=True)),
                ('politician_name', models.TextField(blank=True, db_column='politician_name', null=True)),
                ('party', models.TextField(blank=True, db_column='party', null=True)),
                ('ayes_vote', models.TextField(blank=True, db_column='ayes_vote', null=True)),
                ('noes_vote', models.TextField(blank=True, db_column='noes_vote', null=True)),
            ],
            options={
                'db_table': 'hrepsVotePatterns',
            },
        ),
    ]
